name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push container
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy telegram-bot \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars \
TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }},\
RONGRID_API_KEY=${{ secrets.RONGRID_API_KEY }},\
OWNER_PASSWORD=${{ secrets.OWNER_PASSWORD }},\
GOOGLE_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
